# -*- coding: utf-8 -*-
"""【課題】リスト/ディクショナリを使いこなそう.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLBFgna5g5FbIaijWZ5Wrf8RMHDKz_Fd
"""

#【課題】リスト/ディクショナリを使いこなそう　　≪リスト：array≫

#リスト：array
array=["月曜日は晴れです","火曜日は雨です","水曜日は晴れです","木曜日は晴れです","金曜日は曇りです","土曜日は曇りのち雨です","日曜日は雷雨です"]
print(array[2])

#【課題】リスト/ディクショナリを使いこなそう　　≪ディクショナリ≫

#ディクショナリ
dictionary = {"mon": "晴れ", "tue": "雨", "wed": "晴れ", "thu": "晴れ", "fri": "曇り", "sat": "曇りのち雨", "sun": "雷雨"}

print(dictionary["wed"])